### ISSUE TITLE
Where is util's evaluation code?

### ISSUE THREAD

**Issue by Soo95** [naivete5656/WSISPDR#2]
Hi, Thanks for sharing your work!

I want to know how to evaluate mDice score, so I've searched Evaluation code.
It may be in util's EvaluationMethods, but I couldn't find it.

Would you tell me where the evaluation code locates?

**Comment by naivete5656** [comment]
Sorry, I did not upload the code.
I'll add.

**Comment by Soo95** [comment]
@naivete5656 
Thanks a lot!
