### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by UsamaI000** [naivete5656/WSISPDR#4]
Hi, 
I wanted to try your code on a dataset which has centroid (x,y) position given. Kindly, can you tell me what "frame" refers to in your txt file which has 3 things "frame", "x", "y". 
Does "frame" refers to image name in your dataset ?

**Comment by naivete5656** [comment]
Thanks for your interest.

I use frame since I use sequence data.
If you don't use a sequence data, the frame would be the name of the image.

**Comment by UsamaI000** [comment]
Thanks
