### ISSUE TITLE
Where is GCmex1.9.tar.gz?

### ISSUE THREAD

**Issue by masato-mouse** [naivete5656/WSISPDR#5]
I tried below command. But it occur error about gzip: stdin: not in gzip format.
command: wget http://www.wisdom.weizmann.ac.il/~bagon/matlab_code/GCmex1.9.tar.gz

Consiering, I can't found above URL and GCmex1.9.tar.gz

Please teach me Solutions

**Comment by naivete5656** [comment]
Thank you for your interest in my research.
We used the following graph-cut package. 
Please go to following URL and download it.
https://jp.mathworks.com/matlabcentral/fileexchange/38555-kernel-graph-cut-image-segmentation

Previously, the source code is uploaded on the URL of wget.
But now, the url of the source code seems to have changed.
 We just used this grach-cut library. 
Ths, we don't know the detail location of kernel graph-cut library. Please ask the library writer for more details.

**Comment by masato-mouse** [comment]
Thank you for replying.
I listen to writer.
